### ISSUE TITLE
ImportError: cannot import name _fitpack

### ISSUE THREAD

**Issue by Jumpet** [soft-matter/trackpy-examples#22]
Hello @tacaswell  and @danielballan again,

I am trying to run some code for data I went through over the weekend. I was able to get it to run but now I am running into another issue.
With no changes in the code besides the time between then and now I'm gettting a crippling error that says, ImportError: cannot import name _fitpack

How do I resolve this.?/what is _fitpack?

 most recent calls
runfile('C:/Users/Zach/.spyder2/water example.py', wdir='C:/Users/Zach/.spyder2')
Traceback (most recent call last):

  File "<ipython-input-21-e5021a68ed5c>", line 1, in <module>
    runfile('C:/Users/Zach/.spyder2/water example.py', wdir='C:/Users/Zach/.spyder2')

  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Zach/.spyder2/water example.py", line 20, in <module>
    import trackpy as tp

  File "C:\Anaconda\lib\site-packages\trackpy\__init__.py", line 5, in <module>
    from trackpy.api import *

  File "C:\Anaconda\lib\site-packages\trackpy\api.py", line 4, in <module>
    from .motion import *

  File "C:\Anaconda\lib\site-packages\trackpy\motion.py", line 8, in <module>
    from scipy import interpolate

  File "C:\Anaconda\lib\site-packages\scipy\interpolate\__init__.py", line 160, in <module>
    from .interpolate import *

  File "C:\Anaconda\lib\site-packages\scipy\interpolate\interpolate.py", line 24, in <module>
    from . import fitpack

  File "C:\Anaconda\lib\site-packages\scipy\interpolate\fitpack.py", line 31, in <module>
    from . import _fitpack

ImportError: cannot import name _fitpack

**Comment by tacaswell** [comment]
Your scipy installation is broken.  I would try re-installing in a fresh enviroment, if that does not work this should go to the continuum support lists.
